name: Deploy Shiny App on PR to Development or Main Branch

on:
  pull_request:
    types: [closed]  # Trigger when PR is closed
    branches:
      - main  
  workflow_dispatch:  # Optional manual trigger

jobs:
  
  deploy-main:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
   
    - name: Deploy to shinyapps.io (Production)
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN_DDI_TALENT }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET_DDI_TALENT }}
      run: |
        rsconnect deploy shiny ./ \
        --account ddi-talent \
        --server shinyapps.io \
        --token $SHINYAPPS_TOKEN \
        --secret $SHINYAPPS_SECRET \
        -a 13183414 --title R_interactive_tutorial
