name: Deploy Shiny App on PR to Development or Main Branch

on:
  push
    branches:
      - main

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install R and required packages
        run: |
          sudo apt-get update
          sudo apt-get install r-base
          Rscript -e "install.packages('rsconnect')"

      - name: Deploy application
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN_DDI_TALENT }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET_DDI_TALENT }}
        run: |
          Rscript -e rsconnect::setAccountInfo(name='ddi-talent', token='SHINYAPPS_TOKEN', secret='SHINYAPPS_SECRET')
          Rscript -e "rsconnect::deployApp(appFiles='HDS_InteractiveTutorial/RBasic.Rmd', appId=13183414, appTitle='R_interactive_tutorial')"

