name: Deploy Shiny App on PR to Development or Main Branch

on:
  pull_request:
    types: [closed]  # Trigger when PR is closed
    branches:
      - develop
      - main  
  workflow_dispatch:  # Optional manual trigger

jobs:
  deploy-main:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install R and required packages
        run: |
          Rscript -e "dir.create('~/R', showWarnings = FALSE)"
          Rscript -e "install.packages('rsconnect', repos='https://cloud.r-project.org', lib='~/R')"
          Rscript -e ".libPaths('~/R')"

      - name: Deploy application
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN_DDI_TALENT }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET_DDI_TALENT }}
        run: |
          Rscript -e "library(rsconnect, lib.loc='~/R'); \
                      rsconnect::setAccountInfo(name='ddi-talent', \
                                                token=Sys.getenv('SHINYAPPS_TOKEN'), \
                                                secret=Sys.getenv('SHINYAPPS_SECRET')); \
                      rsconnect::deployApp(appFiles='HDS_InteractiveTutorial/RBasic.Rmd', \
                                           appId=13183414, \
                                           appTitle='R_interactive_tutorial')"