name: Deploy Shiny App on PR to Development or Main Branch

on:
  pull_request:
    types: [closed]  # Trigger when PR is closed
    branches:
      - develop
      - main  
  workflow_dispatch:  # Optional manual trigger

jobs:
  deploy-main:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install system dependencies required by R and renv
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev pandoc

      # Install R, renv, and restore environment from renv.lock
      - name: Set up R and renv
        run: |
          # Install R if necessary (this step can be adjusted if a specific R version is required)
          sudo apt-get install -y r-base
          # Install renv if not available
          sudo Rscript -e "install.packages('renv')"
          # Restore the environment using the renv.lock file
          sudo Rscript -e "renv::restore()"
          
      - name: Deploy application
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN_DDI_TALENT }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET_DDI_TALENT }}
        run: |
          Rscript -e "library(rsconnect); \
                      rsconnect::setAccountInfo(name='ddi-talent', \
                                                token=Sys.getenv('SHINYAPPS_TOKEN'), \
                                                secret=Sys.getenv('SHINYAPPS_SECRET')); \
                      rsconnect::deployApp(appFiles='RBasic.Rmd', \
                                           appId=13183414, \
                                           appTitle='R_interactive_tutorial')"
                                           appTitle='R_interactive_tutorial')"