name: Deploy Shiny App on PR to Development or Main Branch

on:
  pull_request:
    types: [closed]  # Trigger when PR is closed
    branches:
      - develop
      - main  
  workflow_dispatch:  # Optional manual trigger

jobs:
  deploy-main:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install system dependencies for R packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev pandoc zlib1g-dev \
                                  libharfbuzz-dev libfribidi-dev libfontconfig1-dev

      # Set up custom library directory to avoid permission issues
      - name: Set up custom library directory
        run: |
          mkdir -p ~/.R/renv_library  # Create a custom directory for R libraries
          echo 'R_LIBS_USER="~/.R/renv_library"' >> ~/.Renviron

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'


      # Install and restore with renv, using a custom library path
      - name: Install and Restore with renv
        run: |
          Rscript -e "Sys.setenv(R_LIBS_USER='~/.R/renv_library'); install.packages('renv')"
          Rscript -e "Sys.setenv(R_LIBS_USER='~/.R/renv_library'); renv::restore()"
          
      - name: Deploy application
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN_DDI_TALENT }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET_DDI_TALENT }}
        run: |
          Rscript -e "library(rsconnect); \
                      rsconnect::setAccountInfo(name='ddi-talent', \
                                                token=Sys.getenv('SHINYAPPS_TOKEN'), \
                                                secret=Sys.getenv('SHINYAPPS_SECRET')); \
                      rsconnect::deployApp(appFiles='RBasic.Rmd', \
                                           appId=13183414, \
                                           appTitle='R_interactive_tutorial')"
                                           appTitle='R_interactive_tutorial')"